import { __ } from "@wordpress/i18n";

export type SettingsSearchItem = {
    id: string;
    menuKey: string;
    sectionTitle: string;
    sectionIcon: string;
    title: string;
    description?: string;
    keywords: string[];
};

export const SETTINGS_SEARCH_INDEX: SettingsSearchItem[] = [
    // ── Accounts ──────────────────────────────────────────────
    {
        id: "connection_type",
        menuKey: "accounts",
        sectionTitle: __("Accounts", "ninja-drive"),
        sectionIcon: "contacts_product",
        title: __("Connection Type", "ninja-drive"),
        keywords: [
            "automatic",
            "manual",
            "one click",
            "google app",
            "sign in",
            "oauth",
            "client id",
            "client secret",
            "redirect",
            "connect",
        ],
    },
    {
        id: "authorization_info",
        menuKey: "accounts",
        sectionTitle: __("Accounts", "ninja-drive"),
        sectionIcon: "contacts_product",
        title: __("Authorization & Data", "ninja-drive"),
        description: __(
            "Requested scopes, data privacy, and permissions",
            "ninja-drive",
        ),
        keywords: [
            "scopes",
            "data",
            "privacy",
            "permissions",
            "drive",
            "access",
            "authorize",
            "token",
            "encrypted",
            "storage",
        ],
    },
    {
        id: "connected_accounts",
        menuKey: "accounts",
        sectionTitle: __("Accounts", "ninja-drive"),
        sectionIcon: "contacts_product",
        title: __("Connected Accounts", "ninja-drive"),
        keywords: ["profile", "login", "google account", "add account"],
    },

    // ── Advanced ──────────────────────────────────────────────
    {
        id: "workspace_domain",
        menuKey: "advanced",
        sectionTitle: __("Advanced", "ninja-drive"),
        sectionIcon: "category_search",
        title: __("Workspace Domain", "ninja-drive"),
        description: __(
            "Google Workspace domain for exclusive document sharing",
            "ninja-drive",
        ),
        keywords: [
            "domain",
            "google workspace",
            "g suite",
            "sharing",
            "public access",
            "document sharing",
        ],
    },
    {
        id: "sharing_permission",
        menuKey: "advanced",
        sectionTitle: __("Advanced", "ninja-drive"),
        sectionIcon: "category_search",
        title: __("Manage Sharing Permissions", "ninja-drive"),
        keywords: [
            "sharing",
            "permissions",
            "document sharing",
            "auto manage",
            "manual",
        ],
    },
    {
        id: "allow_dot_extension",
        menuKey: "advanced",
        sectionTitle: __("Advanced", "ninja-drive"),
        sectionIcon: "category_search",
        title: __("Show File Extensions in URLs", "ninja-drive"),
        keywords: [
            "file extension",
            "url",
            "jpg",
            "png",
            "pdf",
            "dot extension",
            "filename",
        ],
    },
    {
        id: "redirection",
        menuKey: "advanced",
        sectionTitle: __("Advanced", "ninja-drive"),
        sectionIcon: "category_search",
        title: __("Redirection", "ninja-drive"),
        description: __(
            "Redirect or Proxy mode for loading Google Drive files",
            "ninja-drive",
        ),
        keywords: [
            "redirect",
            "proxy",
            "media library",
            "file loading",
            "google drive files",
        ],
    },
    {
        id: "delete_data_on_uninstall",
        menuKey: "advanced",
        sectionTitle: __("Advanced", "ninja-drive"),
        sectionIcon: "category_search",
        title: __("Delete Data on Uninstall", "ninja-drive"),
        keywords: [
            "uninstall",
            "delete",
            "cleanup",
            "remove data",
            "cache",
            "accounts",
            "settings",
        ],
    },

    // ── Appearance ────────────────────────────────────────────
    {
        id: "theme_color",
        menuKey: "appearance",
        sectionTitle: __("Appearance", "ninja-drive"),
        sectionIcon: "format_paint",
        title: __("Theme Color", "ninja-drive"),
        keywords: [
            "primary color",
            "accent",
            "brand color",
            "color picker",
            "customize",
        ],
    },
    {
        id: "theme_style",
        menuKey: "appearance",
        sectionTitle: __("Appearance", "ninja-drive"),
        sectionIcon: "format_paint",
        title: __("Theme Style", "ninja-drive"),
        description: __(
            "Light Mode, Dark Mode, or System Theme",
            "ninja-drive",
        ),
        keywords: [
            "light mode",
            "dark mode",
            "system theme",
            "appearance",
            "night mode",
        ],
    },
    {
        id: "preloader",
        menuKey: "appearance",
        sectionTitle: __("Appearance", "ninja-drive"),
        sectionIcon: "format_paint",
        title: __("Preloader", "ninja-drive"),
        description: __(
            "Loading animation while content is loading",
            "ninja-drive",
        ),
        keywords: ["loading", "spinner", "loader", "animation"],
    },
    {
        id: "custom_css",
        menuKey: "appearance",
        sectionTitle: __("Appearance", "ninja-drive"),
        sectionIcon: "format_paint",
        title: __("Custom CSS", "ninja-drive"),
        keywords: ["css", "custom styles", "code", "styling"],
    },

    // ── Integrations ──────────────────────────────────────────
    {
        id: "integration_media_library",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Media Library Integration", "ninja-drive"),
        keywords: ["media", "library", "wordpress media", "google drive"],
    },
    {
        id: "integration_classic_editor",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Classic Editor", "ninja-drive"),
        keywords: ["classic editor", "tinymce", "editor"],
    },
    {
        id: "integration_gutenberg",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Gutenberg Editor", "ninja-drive"),
        keywords: ["gutenberg", "block editor", "editor", "blocks"],
    },
    {
        id: "integration_elementor",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Elementor", "ninja-drive"),
        keywords: ["elementor", "page builder", "builder"],
    },
    {
        id: "integration_woocommerce",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("WooCommerce", "ninja-drive"),
        keywords: ["woocommerce", "shop", "ecommerce", "products"],
    },
    {
        id: "integration_edd",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Easy Digital Downloads", "ninja-drive"),
        keywords: ["easy digital downloads", "edd", "downloads", "ecommerce"],
    },
    {
        id: "integration_tutor_lms",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Tutor LMS", "ninja-drive"),
        keywords: ["tutor", "lms", "learning", "courses"],
    },
    {
        id: "integration_elementor_form",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Elementor Form Upload", "ninja-drive"),
        keywords: [
            "elementor form",
            "form upload",
            "file upload",
            "elementor",
        ],
    },
    {
        id: "integration_contact_form_7",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Contact Form 7", "ninja-drive"),
        keywords: ["contact form 7", "cf7", "form", "contact"],
    },
    {
        id: "integration_wp_forms",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("WP Forms", "ninja-drive"),
        keywords: ["wp forms", "form", "builder"],
    },
    {
        id: "integration_ninja_forms",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Ninja Forms", "ninja-drive"),
        keywords: ["ninja forms", "form", "builder"],
    },
    {
        id: "integration_gravity_forms",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Gravity Forms", "ninja-drive"),
        keywords: ["gravity forms", "form", "builder"],
    },
    {
        id: "integration_formidable_forms",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Formidable Forms", "ninja-drive"),
        keywords: ["formidable forms", "form", "builder"],
    },
    {
        id: "integration_fluent_forms",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("Fluent Forms", "ninja-drive"),
        keywords: ["fluent forms", "form", "builder"],
    },
    {
        id: "integration_master_study_lms",
        menuKey: "integrations",
        sectionTitle: __("Integrations", "ninja-drive"),
        sectionIcon: "automation",
        title: __("MasterStudy LMS", "ninja-drive"),
        keywords: ["masterstudy", "lms", "learning", "courses"],
    },

    // ── Tools ─────────────────────────────────────────────────
    {
        id: "auto_save",
        menuKey: "tools",
        sectionTitle: __("Tools", "ninja-drive"),
        sectionIcon: "handyman",
        title: __("Enable Auto Save", "ninja-drive"),
        description: __(
            "Automatically save settings when changes are made",
            "ninja-drive",
        ),
        keywords: ["auto save", "autosave", "settings save"],
    },
    {
        id: "export_data",
        menuKey: "tools",
        sectionTitle: __("Tools", "ninja-drive"),
        sectionIcon: "handyman",
        title: __("Export Data", "ninja-drive"),
        description: __(
            "Export settings and shortcode widgets as JSON",
            "ninja-drive",
        ),
        keywords: ["export", "backup", "json", "shortcode widgets"],
    },
    {
        id: "import_data",
        menuKey: "tools",
        sectionTitle: __("Tools", "ninja-drive"),
        sectionIcon: "handyman",
        title: __("Import Data", "ninja-drive"),
        description: __(
            "Import settings from a previously exported JSON file",
            "ninja-drive",
        ),
        keywords: ["import", "restore", "json"],
    },
    {
        id: "reset_settings",
        menuKey: "tools",
        sectionTitle: __("Tools", "ninja-drive"),
        sectionIcon: "handyman",
        title: __("Reset Settings", "ninja-drive"),
        description: __(
            "Reset all settings to their default values",
            "ninja-drive",
        ),
        keywords: ["reset", "default", "factory reset", "clear all"],
    },

];
